/**
 * `@shmup/core` — the platform-agnostic heart of Shmup Cup.
 *
 * Pure TypeScript: no DOM, WebGL, Web Audio, Node or platform (`tizen`, `webapis`,
 * `electron`) APIs — enforced by `tsconfig.json` (ES2018 lib only) and ESLint.
 * Hosts provide a {@link Platform}; presentation packages implement
 * {@link IRenderer} / {@link IAudio}.
 *
 * This entry point exports the implemented (and partial) public API. Placeholder modules
 * under `src/<module>/` (weapons, bosses, scoring, …) are exported here as they get
 * implemented — `bullets` and `rank` joined with plan step M1-09, `weapons` and `options` with
 * M1-10, `powerups` and `shields` with M1-11, `scoring` and `fx` with M1-12, `bosses` with M1-13,
 * `ui` (UI kit, HUD) and `scenes` (scene stack and flow) with M1-16, `save` (versioned saves,
 * hi-score tables) and the `config` user options with M1-17, the `debug` controls and counters and
 * `replay` (recording, playback, desync detection) with M1-19; the difficulty presets, rank growth,
 * extends and continues with M2-01; the pattern DSL (compiler and interpreter), bending lasers,
 * cancel point items, the scoring rules and the bullet palettes with M2-02; the meter arsenal
 * (Types B–D, Weapon Edit, the `!` / `?` choices, the weapon select) with M2-03.
 *
 * @packageDocumentation
 */

export { defineModule, type ModuleInfo, type ModuleStatus } from './module-info.js';

export {
  RNG_STATE_WORDS,
  createRng,
  createRngStreams,
  type Rng,
  type RngState,
  type RngStreams,
} from './rng/index.js';

export {
  ANGLE_MASK,
  ANGLE_QUARTER,
  ANGLE_UNITS,
  EASINGS,
  angleDelta,
  approach,
  atan2B,
  clamp,
  cosB,
  lerp,
  quantizeAngle,
  sinB,
  turnToward,
  wrapAngle,
  type BinaryAngle,
  type EasingFn,
  type EasingName,
} from './math/index.js';

export { ATAN_TABLE, ATAN_TABLE_STEPS, SIN_TABLE_Q16, TRIG_SCALE } from './math/trig-table.js';

export {
  DEFAULT_EVENT_QUEUE_CAPACITY,
  FX_CUES,
  FX_CUE_NAMES,
  MUSIC_CUES,
  MUSIC_CUE_NAMES,
  SFX_CUES,
  SFX_CUE_NAMES,
  SIM_EVENT_KIND_NAMES,
  SfxPriority,
  SimEventKind,
  UserOptionKind,
  createEventQueue,
  type EventQueue,
  type FxCue,
  type MusicCue,
  type SfxCue,
  type SimEvent,
} from './events/index.js';

export {
  createPool,
  createSoaPool,
  type Pool,
  type SoaArray,
  type SoaArrayFor,
  type SoaFieldType,
  type SoaFields,
  type SoaPool,
  type SoaSchema,
} from './pools/index.js';

export {
  Action,
  ACTION_NAMES,
  INPUT_CONTEXTS,
  MAX_PLAYERS,
  commitPlayerInput,
  copyInputSnapshot,
  createInputSnapshot,
  hasAction,
  resetInputSnapshot,
  type ActionMask,
  type ActionName,
  type InputContext,
  type InputDeviceKind,
  type InputSnapshot,
  type PlayerInput,
} from './input/index.js';

export {
  createHeadlessPlatform,
  createMemoryStorage,
  type HeadlessPlatform,
  type Platform,
  type PlatformAudio,
  type PlatformCaps,
  type PlatformDisplay,
  type PlatformId,
  type PlatformInput,
  type PlatformLifecycle,
  type PlatformStorage,
} from './platform/index.js';

export {
  DEATH_PENALTY_PRESETS,
  DEFAULT_AUTO_POWER_UP_ORDER,
  MEGA_CHOICES,
  SHIELD_CHOICES,
  WEAPON_EDIT_SLOTS,
  arsenalMatches,
  withArsenal,
  DEFAULT_DIFFICULTY_TABLE,
  DEFAULT_GAME_CONFIG,
  BULLET_PALETTES,
  DEFAULT_USER_OPTIONS,
  DIFFICULTY_PRESETS,
  HUD_BAR_HEIGHT,
  INPUT_PROFILE_ID_PATTERN,
  MAX_AUTO_POWER_UP_ORDER,
  MAX_BULLET_SPEED_MUL,
  MAX_CONTINUES,
  MAX_EXTEND_SCORE,
  MAX_RANK_GROWTH,
  METER_SLOT_NAMES,
  MIN_BULLET_SPEED_MUL,
  PLAYFIELD_H,
  PLAYFIELD_W,
  PLAYFIELD_Y,
  VOLUME_LEVELS,
  difficultyOverrides,
  resolveGameConfig,
  resolveUserOptions,
  volumeGain,
  withDifficulty,
  type ArsenalChoice,
  type AudioOptions,
  type DeathPenaltyPreset,
  type DifficultyExtends,
  type DifficultyPreset,
  type DifficultyRules,
  type DifficultyTable,
  type BulletPalette,
  type DisplayOptions,
  type GameConfig,
  type InputOptions,
  type InputProfileChoice,
  type MegaChoice,
  type MeterSlotName,
  type PowerUpMode,
  type ShieldChoice,
  type StageSkip,
  type StartingLoadout,
  type UserOptions,
  type WeaponEdit,
} from './config/index.js';

export {
  DEFAULT_SNAP_TOLERANCE_MS,
  createFixedStepLoop,
  type FixedStepLoop,
  type FixedStepLoopOptions,
} from './loop/index.js';

export {
  DEFAULT_DRAW_LIST_CAPACITY,
  DEFAULT_DRAW_LIST_STRINGS,
  DrawOp,
  LAYER_COUNT,
  LAYER_NAMES,
  LayerId,
  SpriteFlag,
  TextAlign,
  createDrawList,
  createSpriteBatch,
  pushSprite,
  type AudioBus,
  type AudioState,
  type CameraView,
  type DrawList,
  type IAudio,
  type IRenderer,
  type LaserView,
  type BendingLaserView,
  type ParallaxView,
  type RenderFrame,
  type ScreenView,
  type SpriteBatch,
  type SpriteBatchView,
  type TerrainView,
  type TextMetrics,
  type WarningView,
  type WorldView,
} from './presentation/index.js';

export {
  BOSS_VULNERABILITIES,
  CONTENT_FORMAT_VERSION,
  CONTENT_KINDS,
  CONTENT_MIGRATIONS,
  DEFAULT_BOSS_INTRO_TICKS,
  DEFAULT_BOSS_X,
  DEFAULT_BOSS_Y,
  DEFAULT_REVENGE_SPEED,
  DEFAULT_SETTLE_TICKS,
  EMPTY_CONTENT_DB,
  ENEMY_DROPS,
  ENEMY_EXPLOSIONS,
  ENEMY_GROUNDS,
  MAX_BOSS_PARTS,
  MAX_BOSS_PHASES,
  MAX_PATH_LENGTH,
  MAX_STAGE_FLAGS,
  MOVER_TYPES,
  PATH_SAMPLE_STEP,
  REVENGE_PATTERNS,
  STAGE_EVENT_TYPES,
  TILE_ANCHORS,
  TILE_SIZE,
  TILE_TYPES,
  WEAPON_SLOTS,
  bakePath,
  isContentKind,
  loadContent,
  s,
  type BossPartSpec,
  type BossPhaseSpec,
  type BossSpec,
  type BossUntilSpec,
  type BossVulnerability,
  type BoxSpec,
  type ContentDb,
  type ContentFile,
  type ContentFileHeader,
  type ContentKind,
  type ContentMigration,
  type ContentMigrationTable,
  type ContentRefKind,
  type EnemyAnimSpec,
  type EnemyDrop,
  type EnemyExplosion,
  type EnemyGround,
  type EnemyMoverSpec,
  type EnemyRankSpec,
  type EnemyRevengeSpec,
  type EnemySpec,
  type Infer,
  type LoadContentOptions,
  type LoadContentResult,
  type MarginSpec,
  type MoverType,
  type ObjectShape,
  type ObjectValue,
  type PathPointSpec,
  type PathSpec,
  type PathTable,
  type PlayerShipSpec,
  type RefSite,
  type RevengePattern,
  type Schema,
  type HeightfieldProfile,
  type HeightfieldSegment,
  type HeightfieldSpec,
  type StageBossEvent,
  type StageCameraKey,
  type StageCheckpoint,
  type StageEndEvent,
  type StageEvent,
  type StageFlagEvent,
  type StageFormationEvent,
  type StageMusic,
  type StageMusicEvent,
  type StageParallaxLayer,
  type StageParallaxLayerName,
  type StageSpawnEvent,
  type StageSpec,
  type StageSpeedEvent,
  type StageTerrain,
  type StageTilemapSpec,
  type StringTable,
  type TileAnchor,
  type TileSpec,
  type TileType,
  type TilesetSpec,
  type TilesetTables,
  type ValidationIssue,
  type WeaponPresetSpec,
  type WeaponSlot,
  type WeaponSpec,
} from './data/index.js';

export {
  COLLISION_MASKS,
  CollisionLayer,
  DEFAULT_GRID_CAPACITY,
  DEFAULT_GRID_CELL_SIZE,
  TerrainAnchor,
  TerrainType,
  aabbAabb,
  boxHitsTerrain,
  capsuleCircle,
  circleAabb,
  circleCircle,
  createSpatialGrid,
  findCeiling,
  findFloor,
  layersInteract,
  pointSegmentDistanceSq,
  segmentAabb,
  terrainAt,
  terrainRectHit,
  terrainSolidAt,
  type Shape,
  type SpatialGrid,
  type SpatialGridVisitor,
  type TerrainMap,
} from './collision/index.js';

export {
  DEFAULT_PLAYER_SHIP,
  DIAGONAL_SCALE,
  ENTER_END_X,
  ENTER_START_X,
  PLAYER_DEAD_TICKS,
  PLAYER_DYING_TICKS,
  PLAYER_HIT_CAUSE_NAMES,
  PLAYER_STATES,
  PlayerHitCause,
  SPAWN_Y,
  createPlayer,
  createPlayerIntent,
  killPlayer,
  playerBankFrame,
  playerHit,
  playerOut,
  readPlayerIntent,
  resolvePlayerShip,
  respawnPlayer,
  setPlayerState,
  spawnPlayer,
  updatePlayer,
  type PlayerCamera,
  type PlayerIntent,
  type PlayerShip,
  type PlayerState,
} from './player/index.js';

export {
  BOSS_SKIP_LEAD,
  DEBUG_COMMAND_NAMES,
  DEBUG_HASH_INTERVAL,
  DebugCommand,
  FNV_OFFSET_BASIS,
  FNV_PRIME,
  SLOW_MO_STEPS,
  collectDebugCounters,
  createDebugControls,
  createDebugCounters,
  createDebugFlags,
  hashWorld,
  jumpToCheckpoint,
  jumpToNextCheckpoint,
  skipToBoss,
  type DebugControls,
  type DebugCounters,
  type DebugFlags,
  type SlowMo,
} from './debug/index.js';

export {
  AIM_DIRECTIONS,
  BodyAnchor,
  CRAWL_STEP,
  FOLLOW_HISTORY,
  FollowTrack,
  MOVER_NAMES,
  MoverKind,
  SLEEP_FOREVER,
  createMoverContext,
  fireAimed,
  fireDelayed,
  fireHoming,
  fireNWay,
  fireRing,
  fireSpiral,
  fireSpray,
  fireStack,
  moverKindOf,
  rankedWait,
  resumeScript,
  samplePath,
  setMover,
  updateMover,
  type MoverBody,
  type MoverContext,
  type Script,
  type ScriptHolder,
  ACCEL_HAS_MAX,
  ACCEL_HAS_MIN,
  DEFAULT_PATTERN_KIND,
  DEFAULT_PATTERN_SPEED,
  DIRECTION_TYPES,
  DirType,
  EMPTY_PATTERN_BANK,
  ExprOp,
  MAX_BULLET_PROGRAMS,
  MAX_EXPR_STACK,
  MAX_PATTERN_CODE,
  MAX_PATTERN_EMITTERS,
  MAX_PATTERN_LOCALS,
  MAX_PATTERN_PARAMS,
  MAX_PATTERN_WAIT,
  MAX_REPEAT_DEPTH,
  PATTERNS_FILE_SCHEMA,
  PATTERN_RUNNERS,
  PATTERN_STEP_BUDGET,
  PatternOp,
  SPEED_TYPES,
  SpeedType,
  applyExprOp,
  compileExpression,
  compilePatternBank,
  createPatternVm,
  type CollectedPatterns,
  type PatternActionEntry,
  type PatternBank,
  type PatternBulletEntry,
  type PatternBulletSpec,
  type PatternDirection,
  type PatternExpr,
  type PatternHost,
  type PatternNode,
  type PatternRunners,
  type PatternSource,
  type PatternSpeed,
  type PatternSpeedSpec,
  type PatternVm,
  type PatternsFile,
} from './patterns/index.js';

export {
  DEFAULT_SPAWN_SCREEN_X,
  DESPAWN_MARGIN,
  DropKind,
  Enemy,
  EnemyFlag,
  EnemyState,
  GHOST_MARGIN,
  HIT_FLASH_TICKS,
  MAX_ENEMIES,
  MAX_FORMATIONS,
  UNSEEN_MARGIN,
  UNSEEN_TICKS,
  createEnemySystem,
  type EnemyBehavior,
  type EnemyBehaviorLookup,
  type EnemyHost,
  type EnemyOutcomes,
  type EnemySystem,
  type FormationTable,
  type ScriptApi,
} from './enemies/index.js';

export {
  AIM_AT_TARGET,
  BENDING_LASER_HOMING,
  BENDING_LASER_LENGTH,
  BENDING_LASER_LIFE,
  BENDING_LASER_NODES,
  BENDING_LASER_SPEED,
  BENDING_LASER_SPRITE,
  BENDING_LASER_TURN,
  BENDING_LASER_WIDTH,
  BULLET_COLORS,
  BULLET_CULL_MARGIN,
  BULLET_KINDS,
  BULLET_KIND_NAMES,
  BULLET_SCHEMA,
  BULLET_SHAPES,
  BULLET_SPRITES,
  BendingLaserTable,
  BulletFlag,
  BulletKind,
  BulletOrigin,
  BulletShot,
  MAX_BENDING_LASERS,
  MAX_POINT_ITEMS,
  POINT_ITEM_ACCEL,
  POINT_ITEM_HOVER_TICKS,
  POINT_ITEM_LIFETIME,
  POINT_ITEM_MAX_SPEED,
  POINT_ITEM_SCHEMA,
  POINT_ITEM_SPRITE,
  POINT_ITEM_TARGETS,
  fireBendingLaser,
  type BulletProgramRunner,
  type PointItemSchema,
  CANCEL_SPARKLE_LIMIT,
  CancelMode,
  LASER_ACTIVE_TICKS,
  LASER_BLINK_TICKS,
  LASER_FADE_TICKS,
  LASER_GROW_TICKS,
  LASER_SCHEMA,
  LASER_SPRITE,
  LASER_TELEGRAPH_TICKS,
  LASER_WIDTH,
  LaserPhase,
  MAX_BULLET_SPEED,
  MAX_ENEMY_BULLETS,
  MAX_ENEMY_LASERS,
  NO_TARGET_ANGLE,
  UNCHANGED,
  cancelAllBullets,
  createBulletSystem,
  fireLaser,
  spawnBullet,
  type BulletHost,
  type BulletKindSpec,
  type BulletOwner,
  type BulletSchema,
  type BulletSystem,
  type LaserSchema,
  type LaserSource,
} from './bullets/index.js';

export {
  BULLET_SPEED_RANK_CURVE,
  DIFFICULTY_RANK_BASE,
  FIRE_RATE_RANK_CURVE,
  RANK_LOOP1_CAP,
  RANK_MAX,
  RANK_NORMAL,
  RANK_POWER,
  computeRank,
  createRankInputs,
  difficultyRankInputs,
  powerRank,
  rankScale,
  rankSensitivity,
  type RankCurve,
  type RankInputs,
} from './rank/index.js';

export {
  BEHAVIOR_IDS,
  BOSS_BEHAVIOR_IDS,
  DEFAULT_BEHAVIORS,
  DEFAULT_BEHAVIOR_DEFS,
  DEFAULT_BOSS_BEHAVIORS,
  DEFAULT_BOSS_BEHAVIOR_DEFS,
  KNOWN_SCRIPT_IDS,
  checkEnemyBehaviors,
  createBehaviorRegistry,
  createBossBehaviorRegistry,
  defineBehavior,
  defineBossBehavior,
  type BehaviorDef,
  type BehaviorRegistry,
  type BossBehaviorDef,
  type BossBehaviorRegistry,
} from './behaviors/index.js';

export {
  BOSS_BLAST_HIT_STOP_TICKS,
  BOSS_BLAST_SHAKE_TICKS,
  BOSS_CHAIN_INTERVAL,
  BOSS_CHAIN_TICKS,
  BOSS_CLEAR_TICKS,
  BOSS_ENTRY_MARGIN,
  BOSS_MUSIC_FADE_TICKS,
  BOSS_PART_ID_BASE,
  BOSS_STATE_NAMES,
  BOSS_TALLY_TICKS,
  Boss,
  BossHit,
  BossMotion,
  BossPart,
  BossState,
  BossVulnerable,
  EMPTY_BOSS_BEHAVIORS,
  MAX_HIT_TARGETS,
  WARNING_BRAKE_TICKS,
  WARNING_DIM_PERCENT,
  WARNING_MUSIC_FADE_TICKS,
  WARNING_PULSE_TICKS,
  WARNING_TEMPLATE,
  WARNING_TICKS,
  WarningState,
  createBossSystem,
  formatWarningText,
  type BossBehavior,
  type BossBehaviorLookup,
  type BossHost,
  type BossScriptApi,
  type BossSystem,
} from './bosses/index.js';

export {
  MAX_OPTIONS,
  OPTION_ANIM_TICKS,
  OPTION_SPACING,
  OPTION_SPRITE,
  OPTION_TRAIL_CAPACITY,
  OptionGroup,
  createOptionGroup,
  type OptionFormation,
} from './options/index.js';

export {
  DEFAULT_WEAPON_PRESET,
  FULL_LOADOUT_SPEED_LEVEL,
  LASER_SEGMENT_LENGTH,
  Loadout,
  MAX_PLAYER_SHOTS,
  MAX_SHOOTERS,
  MAX_SHOT_HITS,
  MainWeapon,
  PIERCE_TABLES,
  RIPPLE_RING_WIDTH,
  SFX_RATE_TICKS,
  SHOOTERS_PER_PLAYER,
  SHOT_BATCH_CAPACITY,
  SHOT_CULL_MARGIN,
  SHOT_SCHEMA,
  SPREAD_BLAST_SPRITE,
  ShotFlag,
  ShotKind,
  WEAPON_BEHAVIOR_KINDS,
  WEAPON_BEHAVIOR_LABELS,
  WEAPON_BEHAVIOR_PARAMS,
  WEAPON_BEHAVIOR_SLOTS,
  WEAPON_ROLE_COUNT,
  WEAPON_SCRIPT_IDS,
  WEAPON_SPRITES,
  WeaponRole,
  applyLoadoutPreset,
  checkWeaponBehaviors,
  createWeaponSystem,
  resolveArsenal,
  resolveRoleWeapons,
  resolveWeaponPreset,
  weaponLabel,
  weaponsOfSlot,
  type ShotSchema,
  type WeaponBehaviorId,
  type WeaponHost,
  type WeaponSystem,
} from './weapons/index.js';

export {
  FORCE_FIELD,
  FORCE_FIELD_HITS,
  FORCE_FIELD_SPRITE,
  FORCE_FIELD_WEAR_FRAMES,
  SHIELD_CHOICE_SPECS,
  SHIELD_HIT_IFRAMES,
  SHIELD_KIND_NAMES,
  SHIELD_SPECS,
  ShieldHit,
  ShieldKind,
  ShieldState,
  absorbShieldHit,
  clearShield,
  createShieldState,
  grantShield,
  shieldActive,
  shieldSpecOf,
  shieldWearFrame,
  tickShield,
  type ShieldSpec,
} from './shields/index.js';

export {
  CAPSULE_SCORE,
  CAPSULE_SPRITE,
  DEFAULT_METER_CHOICES,
  ITEM_BLINK_TICKS,
  ITEM_CULL_MARGIN,
  ITEM_KINDS,
  ITEM_RADIUS,
  ITEM_SCHEMA,
  ITEM_SPRITES,
  ItemFlag,
  ItemKind,
  MAX_ITEMS,
  MEGA_CRASH_FLASH_TICKS,
  METER_LABELS,
  METER_SLOT_COUNT,
  MegaEffect,
  MeterChoices,
  MeterSlot,
  PICKUP_MAGNET_RANGE,
  PICKUP_MAGNET_SPEED,
  PowerMeter,
  advanceMeter,
  applyDeathPenalty,
  canEquipSlot,
  createPowerMeter,
  createPowerUpSystem,
  equipSlot,
  equippableSlots,
  lifeOptionCount,
  loseOneLevel,
  megaEffectOf,
  meterChoicesOf,
  meterSlotOf,
  type DirectItem,
  type MeterShip,
  type ItemKindSpec,
  type ItemSchema,
  type PowerUpHost,
  type PowerUpOutcomes,
  type PowerUpSystem,
} from './powerups/index.js';

export {
  FLASH_KIND_TICKS,
  FlashKind,
  FxState,
  MAX_FX_TICKS,
  MAX_HIT_STOP_TICKS,
  ShakeMagnitude,
  createFxState,
  requestFlash,
  requestHitStop,
  requestShake,
  shakeAmount,
  tickFx,
  type FxHost,
  type HitStopHost,
} from './fx/index.js';

export {
  DEFAULT_SCORING_RULES,
  MAX_BULLET_CANCEL_POINTS,
  MAX_LIVES,
  MAX_SCORE,
  PlayerScore,
  type ScoringRules,
  ScoreBoard,
  addScore,
  createScoreBoard,
  createScoringSystem,
  markContinue,
  type HiScoreEntry,
  type ScoreHost,
  type ScoringHost,
  type ScoringSystem,
} from './scoring/index.js';

export {
  DEATH_HIT_STOP_TICKS,
  DEATH_MUSIC_DUCK_TICKS,
  DEATH_SHAKE_TICKS,
  ENGINE_SPRITES,
  GRID_MARGIN,
  WORLD_PHASES,
  WORLD_PHASE_NAMES,
  WORLD_STATUSES,
  WorldPhase,
  canContinue,
  continueWorld,
  createWorld,
  resolveWorldStage,
  stepWorld,
  syncWorldView,
  updateWorldRank,
  type PoolRegistry,
  type RegisteredPool,
  type World,
  type WorldCamera,
  type WorldOptions,
  type WorldPhaseEntry,
  type WorldStatus,
  type WorldSystem,
} from './world/index.js';

export {
  STAGE_STATE_SLOTS,
  StageEventCode,
  StageSlot,
  createParallaxView,
  createStageCamera,
  createStageRunner,
  createStageTerrain,
  createTerrainView,
  findEventCursor,
  stageMapWidth,
  updateParallaxView,
  type StageCamera,
  type StageHooks,
  type StageParallaxView,
  type StageRunner,
} from './stage/index.js';

export {
  CONFIRM_STRING_SLOTS,
  Choice,
  Confirm,
  ConfirmChoice,
  DirectionRepeat,
  HUD_COLORS,
  HUD_LAYOUT,
  HUD_METER_FLASH_TICKS,
  HUD_STRING_SLOTS,
  Hud,
  METER_LABEL_FRAMES,
  ListMenu,
  MENU_CONFIRM_BUFFER_TICKS,
  MENU_REPEAT_DELAY,
  MENU_REPEAT_INTERVAL,
  MenuItemKind,
  MenuResult,
  Slider,
  Toggle,
  UI_COLORS,
  UI_SPRITES,
  buildHud,
  confirmTick,
  createChoice,
  createConfirm,
  createHud,
  createListMenu,
  createSlider,
  createToggle,
  drawConfirm,
  drawMenu,
  drawPanel,
  menuResultSfx,
  menuStringSlots,
  menuTick,
  meterLabelFrame,
  repeatDirections,
  resolveUiSprites,
  type ListMenuOptions,
  type MenuItem,
  type MenuItemSpec,
  type MenuLayout,
  type UiSprites,
} from './ui/index.js';

export {
  AUTO_ORDER_LABELS,
  AUTO_ORDER_ROWS,
  AutoOrderScene,
  BootScene,
  CONTINUE_COUNTDOWN_TICKS,
  CONTINUE_LOCK_TICKS,
  ConfirmDialog,
  BULLET_PALETTE_LABELS,
  ConfirmPurpose,
  ContinueScene,
  DifficultyScene,
  GAME_OVER_DELAY_TICKS,
  GAME_OVER_LOCK_TICKS,
  GAME_OVER_TIMEOUT_TICKS,
  GameOverScene,
  GameScene,
  MEGA_CHOICE_LABELS,
  OptionsItem,
  OptionsScene,
  PAUSE_DIM,
  PREVIEW_OPTIONS,
  PREVIEW_SHIP_X,
  PREVIEW_WEAVE_TICKS,
  PauseItem,
  PauseScene,
  SCENE_STACK_DEPTH,
  SHIELD_CHOICE_LABELS,
  STAGE_CLEAR_CONTINUED_TICKS,
  STAGE_CLEAR_DELAY_TICKS,
  STAGE_CLEAR_TALLY_TICKS,
  SceneStack,
  StageClearScene,
  TitleItem,
  TitleScene,
  WEAPON_EDIT_LABEL,
  WEAPON_RANGE_STAGE,
  WeaponSelectItem,
  WeaponSelectScene,
  createSceneFlow,
  createSceneStack,
  mergeMenuInput,
  type InputProfileSetup,
  type Scene,
  type SceneFlow,
  type SceneFlowHost,
  type SceneFlowView,
  type SceneId,
  type SceneStart,
} from './scenes/index.js';

export { createGame, type Game, type GameOptions, type GameState } from './game/index.js';

export {
  REPLAY_FORMAT_VERSION,
  REPLAY_HASH_INTERVAL,
  REPLAY_KIND,
  createPlayback,
  createReplayGame,
  createReplayHeader,
  createReplayRecorder,
  decodeBase64,
  decodeInputRuns,
  decodeReplay,
  encodeBase64,
  encodeInputRuns,
  encodeReplay,
  packReplayInput,
  playReplay,
  type DesyncReport,
  type PlaybackOptions,
  type RecorderOptions,
  type Replay,
  type ReplayHeader,
  type ReplayHeaderOptions,
  type ReplayJson,
  type ReplayPlayback,
  type ReplayRecorder,
  type ReplayRun,
} from './replay/index.js';

export {
  DEFAULT_HI_SCORE_NAME,
  HI_SCORE_NAME_MAX,
  HI_SCORE_TABLE_SIZE,
  MAX_HI_SCORE_TABLES,
  SAVE_CORRUPT_KEY,
  SAVE_MIGRATIONS,
  SAVE_STORAGE_KEY,
  SAVE_VERSION,
  SaveStore,
  createDefaultSave,
  createHiScoreEntry,
  createSaveStore,
  hiScoreModeKey,
  insertHiScore,
  loadSave,
  migrateSave,
  parseSave,
  sanitizeSave,
  serializeSave,
  writeSave,
  type HiScoreInsert,
  type LoadedSave,
  type ParsedSave,
  type SaveData,
  type SaveMigration,
  type SaveStats,
  type SaveStatus,
} from './save/index.js';
