/**
 * `@shmup/core` — the platform-agnostic heart of Shmup Cup.
 *
 * Pure TypeScript: no DOM, WebGL, Web Audio, Node or platform (`tizen`, `webapis`,
 * `electron`) APIs — enforced by `tsconfig.json` (ES2018 lib only) and ESLint.
 * Hosts provide a {@link Platform}; presentation packages implement
 * {@link IRenderer} / {@link IAudio}.
 *
 * This entry point exports the implemented (and partial) public API. Placeholder modules
 * under `src/<module>/` (weapons, bosses, scoring, …) are exported here as they get
 * implemented — `bullets` and `rank` joined with plan step M1-09.
 *
 * @packageDocumentation
 */

export { defineModule, type ModuleInfo, type ModuleStatus } from './module-info.js';

export {
  RNG_STATE_WORDS,
  createRng,
  createRngStreams,
  type Rng,
  type RngState,
  type RngStreams,
} from './rng/index.js';

export {
  ANGLE_MASK,
  ANGLE_QUARTER,
  ANGLE_UNITS,
  EASINGS,
  angleDelta,
  approach,
  atan2B,
  clamp,
  cosB,
  lerp,
  quantizeAngle,
  sinB,
  turnToward,
  wrapAngle,
  type BinaryAngle,
  type EasingFn,
  type EasingName,
} from './math/index.js';

export { ATAN_TABLE, ATAN_TABLE_STEPS, SIN_TABLE_Q16, TRIG_SCALE } from './math/trig-table.js';

export {
  DEFAULT_EVENT_QUEUE_CAPACITY,
  FX_CUES,
  FX_CUE_NAMES,
  MUSIC_CUES,
  MUSIC_CUE_NAMES,
  SFX_CUES,
  SFX_CUE_NAMES,
  SIM_EVENT_KIND_NAMES,
  SimEventKind,
  createEventQueue,
  type EventQueue,
  type FxCue,
  type MusicCue,
  type SfxCue,
  type SimEvent,
} from './events/index.js';

export {
  createPool,
  createSoaPool,
  type Pool,
  type SoaArray,
  type SoaArrayFor,
  type SoaFieldType,
  type SoaFields,
  type SoaPool,
  type SoaSchema,
} from './pools/index.js';

export {
  Action,
  ACTION_NAMES,
  INPUT_CONTEXTS,
  MAX_PLAYERS,
  commitPlayerInput,
  copyInputSnapshot,
  createInputSnapshot,
  hasAction,
  resetInputSnapshot,
  type ActionMask,
  type ActionName,
  type InputContext,
  type InputDeviceKind,
  type InputSnapshot,
  type PlayerInput,
} from './input/index.js';

export {
  createHeadlessPlatform,
  createMemoryStorage,
  type HeadlessPlatform,
  type Platform,
  type PlatformAudio,
  type PlatformCaps,
  type PlatformDisplay,
  type PlatformId,
  type PlatformInput,
  type PlatformLifecycle,
  type PlatformStorage,
} from './platform/index.js';

export {
  DEFAULT_GAME_CONFIG,
  HUD_BAR_HEIGHT,
  PLAYFIELD_H,
  PLAYFIELD_W,
  PLAYFIELD_Y,
  resolveGameConfig,
  type DeathPenaltyPreset,
  type DifficultyPreset,
  type GameConfig,
  type PowerUpMode,
} from './config/index.js';

export {
  DEFAULT_SNAP_TOLERANCE_MS,
  createFixedStepLoop,
  type FixedStepLoop,
  type FixedStepLoopOptions,
} from './loop/index.js';

export {
  DEFAULT_DRAW_LIST_CAPACITY,
  DEFAULT_DRAW_LIST_STRINGS,
  DrawOp,
  LAYER_COUNT,
  LAYER_NAMES,
  LayerId,
  SpriteFlag,
  TextAlign,
  createDrawList,
  createSpriteBatch,
  pushSprite,
  type AudioBus,
  type AudioState,
  type CameraView,
  type DrawList,
  type IAudio,
  type IRenderer,
  type LaserView,
  type ParallaxView,
  type RenderFrame,
  type ScreenView,
  type SpriteBatch,
  type SpriteBatchView,
  type TerrainView,
  type TextMetrics,
  type WorldView,
} from './presentation/index.js';

export {
  CONTENT_FORMAT_VERSION,
  CONTENT_KINDS,
  CONTENT_MIGRATIONS,
  DEFAULT_SETTLE_TICKS,
  EMPTY_CONTENT_DB,
  ENEMY_DROPS,
  ENEMY_EXPLOSIONS,
  ENEMY_GROUNDS,
  MAX_PATH_LENGTH,
  MAX_STAGE_FLAGS,
  MOVER_TYPES,
  PATH_SAMPLE_STEP,
  STAGE_EVENT_TYPES,
  TILE_ANCHORS,
  TILE_SIZE,
  TILE_TYPES,
  WEAPON_SLOTS,
  bakePath,
  isContentKind,
  loadContent,
  s,
  type BoxSpec,
  type ContentDb,
  type ContentFile,
  type ContentFileHeader,
  type ContentKind,
  type ContentMigration,
  type ContentMigrationTable,
  type ContentRefKind,
  type EnemyAnimSpec,
  type EnemyDrop,
  type EnemyExplosion,
  type EnemyGround,
  type EnemyMoverSpec,
  type EnemyRankSpec,
  type EnemySpec,
  type Infer,
  type LoadContentOptions,
  type LoadContentResult,
  type MarginSpec,
  type MoverType,
  type ObjectShape,
  type ObjectValue,
  type PathPointSpec,
  type PathSpec,
  type PathTable,
  type PlayerShipSpec,
  type RefSite,
  type Schema,
  type HeightfieldProfile,
  type HeightfieldSegment,
  type HeightfieldSpec,
  type StageBossEvent,
  type StageCameraKey,
  type StageCheckpoint,
  type StageEndEvent,
  type StageEvent,
  type StageFlagEvent,
  type StageFormationEvent,
  type StageMusic,
  type StageMusicEvent,
  type StageParallaxLayer,
  type StageParallaxLayerName,
  type StageSpawnEvent,
  type StageSpec,
  type StageSpeedEvent,
  type StageTerrain,
  type StageTilemapSpec,
  type StringTable,
  type TileAnchor,
  type TileSpec,
  type TileType,
  type TilesetSpec,
  type TilesetTables,
  type ValidationIssue,
  type WeaponPresetSpec,
  type WeaponSlot,
  type WeaponSpec,
} from './data/index.js';

export {
  COLLISION_MASKS,
  CollisionLayer,
  DEFAULT_GRID_CAPACITY,
  DEFAULT_GRID_CELL_SIZE,
  TerrainAnchor,
  TerrainType,
  aabbAabb,
  boxHitsTerrain,
  capsuleCircle,
  circleAabb,
  circleCircle,
  createSpatialGrid,
  findCeiling,
  findFloor,
  layersInteract,
  pointSegmentDistanceSq,
  segmentAabb,
  terrainAt,
  terrainRectHit,
  terrainSolidAt,
  type Shape,
  type SpatialGrid,
  type SpatialGridVisitor,
  type TerrainMap,
} from './collision/index.js';

export {
  DEFAULT_PLAYER_SHIP,
  DIAGONAL_SCALE,
  ENTER_END_X,
  ENTER_START_X,
  PLAYER_HIT_CAUSE_NAMES,
  PLAYER_STATES,
  PlayerHitCause,
  SPAWN_Y,
  createPlayer,
  createPlayerIntent,
  playerBankFrame,
  playerHit,
  readPlayerIntent,
  resolvePlayerShip,
  setPlayerState,
  spawnPlayer,
  updatePlayer,
  type PlayerCamera,
  type PlayerIntent,
  type PlayerShip,
  type PlayerState,
} from './player/index.js';

export {
  FNV_OFFSET_BASIS,
  FNV_PRIME,
  createDebugFlags,
  hashWorld,
  type DebugCounters,
  type DebugFlags,
} from './debug/index.js';

export {
  AIM_DIRECTIONS,
  BodyAnchor,
  CRAWL_STEP,
  FOLLOW_HISTORY,
  FollowTrack,
  MOVER_NAMES,
  MoverKind,
  SLEEP_FOREVER,
  createMoverContext,
  fireAimed,
  fireDelayed,
  fireHoming,
  fireNWay,
  fireRing,
  fireSpiral,
  fireSpray,
  fireStack,
  moverKindOf,
  rankedWait,
  resumeScript,
  samplePath,
  setMover,
  updateMover,
  type MoverBody,
  type MoverContext,
  type PatternNode,
  type Script,
  type ScriptHolder,
} from './patterns/index.js';

export {
  DEFAULT_SPAWN_SCREEN_X,
  DESPAWN_MARGIN,
  DropKind,
  Enemy,
  EnemyFlag,
  EnemyState,
  GHOST_MARGIN,
  HIT_FLASH_TICKS,
  MAX_ENEMIES,
  MAX_FORMATIONS,
  UNSEEN_MARGIN,
  UNSEEN_TICKS,
  createEnemySystem,
  type EnemyBehavior,
  type EnemyBehaviorLookup,
  type EnemyHost,
  type EnemyOutcomes,
  type EnemySystem,
  type FormationTable,
  type ScriptApi,
} from './enemies/index.js';

export {
  AIM_AT_TARGET,
  BULLET_CULL_MARGIN,
  BULLET_KINDS,
  BULLET_SCHEMA,
  BULLET_SPRITES,
  BulletFlag,
  BulletKind,
  BulletOrigin,
  CANCEL_SPARKLE_LIMIT,
  CancelMode,
  LASER_ACTIVE_TICKS,
  LASER_BLINK_TICKS,
  LASER_FADE_TICKS,
  LASER_GROW_TICKS,
  LASER_SCHEMA,
  LASER_SPRITE,
  LASER_TELEGRAPH_TICKS,
  LASER_WIDTH,
  LaserPhase,
  MAX_BULLET_SPEED,
  MAX_ENEMY_BULLETS,
  MAX_ENEMY_LASERS,
  NO_TARGET_ANGLE,
  UNCHANGED,
  cancelAllBullets,
  createBulletSystem,
  fireLaser,
  spawnBullet,
  type BulletHost,
  type BulletKindSpec,
  type BulletOwner,
  type BulletSchema,
  type BulletSystem,
  type LaserSchema,
  type LaserSource,
} from './bullets/index.js';

export {
  BULLET_SPEED_RANK_CURVE,
  DIFFICULTY_RANK_BASE,
  FIRE_RATE_RANK_CURVE,
  RANK_LOOP1_CAP,
  RANK_MAX,
  RANK_NORMAL,
  computeRank,
  difficultyRankInputs,
  rankScale,
  type RankCurve,
  type RankInputs,
} from './rank/index.js';

export {
  BEHAVIOR_IDS,
  DEFAULT_BEHAVIORS,
  DEFAULT_BEHAVIOR_DEFS,
  KNOWN_SCRIPT_IDS,
  WEAPON_SCRIPT_IDS,
  checkEnemyBehaviors,
  createBehaviorRegistry,
  defineBehavior,
  type BehaviorDef,
  type BehaviorRegistry,
} from './behaviors/index.js';

export {
  ENGINE_SPRITES,
  GRID_MARGIN,
  WORLD_PHASES,
  WORLD_PHASE_NAMES,
  WORLD_STATUSES,
  WorldPhase,
  createWorld,
  resolveWorldStage,
  stepWorld,
  syncWorldView,
  type PoolRegistry,
  type RegisteredPool,
  type World,
  type WorldCamera,
  type WorldOptions,
  type WorldPhaseEntry,
  type WorldStatus,
  type WorldSystem,
} from './world/index.js';

export {
  STAGE_STATE_SLOTS,
  StageEventCode,
  StageSlot,
  createParallaxView,
  createStageCamera,
  createStageRunner,
  createStageTerrain,
  createTerrainView,
  findEventCursor,
  stageMapWidth,
  updateParallaxView,
  type StageCamera,
  type StageHooks,
  type StageParallaxView,
  type StageRunner,
} from './stage/index.js';

export { createGame, type Game, type GameState } from './game/index.js';
